//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounting
    {
        public accounting()
        {
            this.tickets = new HashSet<ticket>();
            this.tran_transaction = new HashSet<tran_transaction>();
        }
    
        public int accountingID { get; set; }
        public int userID { get; set; }
        public double accountingPrices { get; set; }
        public double accountingDiscount { get; set; }
        public double accountingReceive { get; set; }
        public System.DateTime accountingDateTime { get; set; }
        public int accountingTypeID { get; set; }
        public string accountingComment { get; set; }
        public Nullable<int> ticketID { get; set; }
        public Nullable<int> numOfPerson { get; set; }
        public Nullable<int> realNumOfPerson { get; set; }
        public string priceProfileName { get; set; }
        public string cancleProblemComment { get; set; }
    
        public virtual accountingType accountingType { get; set; }
        public virtual sysUser sysUser { get; set; }
        public virtual ICollection<ticket> tickets { get; set; }
        public virtual ICollection<tran_transaction> tran_transaction { get; set; }
    }
}
