//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountingType
    {
        public accountingType()
        {
            this.accountings = new HashSet<accounting>();
        }
    
        public int accountingTypeID { get; set; }
        public string accountingTypeCode { get; set; }
        public string accountingTypeName { get; set; }
    
        public virtual ICollection<accounting> accountings { get; set; }
    }
}
