//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public car()
        {
            this.tickets = new HashSet<ticket>();
        }
    
        public int carID { get; set; }
        public Nullable<int> carTypeID { get; set; }
        public string carModel { get; set; }
        public string carColor { get; set; }
        public string carPlateNumber { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> carBrandID { get; set; }
    
        public virtual car_carBrand car_carBrand { get; set; }
        public virtual car_carType car_carType { get; set; }
        public virtual param_province param_province { get; set; }
        public virtual ICollection<ticket> tickets { get; set; }
    }
}
