//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_carColor
    {
        public car_carColor()
        {
            this.cars = new HashSet<car>();
        }
    
        public int carColorID { get; set; }
        public string carColorName { get; set; }
    
        public virtual ICollection<car> cars { get; set; }
    }
}
