//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_carBrand
    {
        public car_carBrand()
        {
            this.cars = new HashSet<car>();
        }
    
        public int carBrandID { get; set; }
        public string carBrandName { get; set; }
        public Nullable<int> carBrandOrderIndex { get; set; }
    
        public virtual ICollection<car> cars { get; set; }
    }
}
