//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLSCalendar
    {
        public int CalendarId { get; set; }
        public System.DateTime DateValue { get; set; }
        public int DayNumberOfWeek { get; set; }
        public string NameOfDay { get; set; }
        public string NameOfMonth { get; set; }
        public int WeekOfYear { get; set; }
        public int JulianDay { get; set; }
        public bool USAIsBankHoliday { get; set; }
        public string USADayName { get; set; }
    }
}
