//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class param_blackListVehicle
    {
        public int blacklistID { get; set; }
        public string plateNumber { get; set; }
        public Nullable<System.DateTime> blacklistUpdate { get; set; }
    }
}
