//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class param_systemLog
    {
        public int logId { get; set; }
        public int logType { get; set; }
        public string logDes { get; set; }
        public System.DateTime logTime { get; set; }
    }
}
