//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class parkingArea
    {
        public parkingArea()
        {
            this.sysGates = new HashSet<sysGate>();
        }
    
        public int parkingAreaID { get; set; }
        public string parkingAreaName { get; set; }
        public int parkingAreaSlotAvaliable { get; set; }
        public bool parkingAreaActive { get; set; }
        public System.TimeSpan parkingAreaOpenTime { get; set; }
        public System.TimeSpan parkingAreaCloseTime { get; set; }
        public string parkingAreaComment { get; set; }
        public int OnwerCompanyID { get; set; }
    
        public virtual sysOwnerCompany sysOwnerCompany { get; set; }
        public virtual ICollection<sysGate> sysGates { get; set; }
    }
}
