//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_permission
    {
        public sys_permission()
        {
            this.sys_sysUserType_permission = new HashSet<sys_sysUserType_permission>();
        }
    
        public int permissionID { get; set; }
        public string permissionName { get; set; }
    
        public virtual ICollection<sys_sysUserType_permission> sys_sysUserType_permission { get; set; }
    }
}
