//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysGate
    {
        public sysGate()
        {
            this.tran_transaction = new HashSet<tran_transaction>();
            this.tran_transaction1 = new HashSet<tran_transaction>();
        }
    
        public int gateID { get; set; }
        public string gateName { get; set; }
        public string gateLocation { get; set; }
        public string gateDirection { get; set; }
        public int parkingAreaID { get; set; }
        public bool gateIsAutoType { get; set; }
    
        public virtual parkingArea parkingArea { get; set; }
        public virtual ICollection<tran_transaction> tran_transaction { get; set; }
        public virtual ICollection<tran_transaction> tran_transaction1 { get; set; }
    }
}
