//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysOwnerCompany
    {
        public sysOwnerCompany()
        {
            this.parkingAreas = new HashSet<parkingArea>();
            this.sysUsers = new HashSet<sysUser>();
        }
    
        public int ownerCompanyID { get; set; }
        public string ownerCompanyName { get; set; }
        public string ownerCompanyCodeName { get; set; }
        public bool ownerCompanyActive { get; set; }
        public string ownerCompanyAddr { get; set; }
        public string ownerCompanyTel { get; set; }
        public string ownerCompanyEmail { get; set; }
        public string ownerCompanyFax { get; set; }
    
        public virtual ICollection<parkingArea> parkingAreas { get; set; }
        public virtual ICollection<sysUser> sysUsers { get; set; }
    }
}
