//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysReader
    {
        public sysReader()
        {
            this.sys_gate_Match_reader = new HashSet<sys_gate_Match_reader>();
        }
    
        public int readerID { get; set; }
        public string readerType { get; set; }
        public string readerName { get; set; }
    
        public virtual ICollection<sys_gate_Match_reader> sys_gate_Match_reader { get; set; }
    }
}
