//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysUser
    {
        public sysUser()
        {
            this.accountings = new HashSet<accounting>();
            this.sysUserLogs = new HashSet<sysUserLog>();
            this.tickets = new HashSet<ticket>();
            this.tran_priceProfileChangeLog = new HashSet<tran_priceProfileChangeLog>();
            this.tran_transaction = new HashSet<tran_transaction>();
            this.tran_transaction1 = new HashSet<tran_transaction>();
        }
    
        public int sysUserID { get; set; }
        public string sysUserLoginName { get; set; }
        public string sysUserPassword { get; set; }
        public string sysUserName { get; set; }
        public string sysUserTel { get; set; }
        public string sysUserPhone { get; set; }
        public string sysUserEmail { get; set; }
        public string sysUserAddr { get; set; }
        public System.DateTime sysUserExpiryDate { get; set; }
        public bool sysUserActive { get; set; }
        public Nullable<int> OwnerCompanyID { get; set; }
        public Nullable<int> sysUserTypeID { get; set; }
    
        public virtual ICollection<accounting> accountings { get; set; }
        public virtual sysOwnerCompany sysOwnerCompany { get; set; }
        public virtual sysUserType sysUserType { get; set; }
        public virtual ICollection<sysUserLog> sysUserLogs { get; set; }
        public virtual ICollection<ticket> tickets { get; set; }
        public virtual ICollection<tran_priceProfileChangeLog> tran_priceProfileChangeLog { get; set; }
        public virtual ICollection<tran_transaction> tran_transaction { get; set; }
        public virtual ICollection<tran_transaction> tran_transaction1 { get; set; }
    }
}
