//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketType
    {
        public ticketType()
        {
            this.tickets = new HashSet<ticket>();
        }
    
        public int ticketTypeId { get; set; }
        public string ticketTypeName { get; set; }
        public string ticketTypeDes { get; set; }
        public string ticketTypePolicy { get; set; }
    
        public virtual ICollection<ticket> tickets { get; set; }
    }
}
