//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketMember
    {
        public ticketMember()
        {
            this.tickets = new HashSet<ticket>();
        }
    
        public int ticketMemberID { get; set; }
        public string ticketMemberName { get; set; }
        public string ticketMemberTel { get; set; }
        public string ticketMemberAddr { get; set; }
        public string ticketMemberEmail { get; set; }
        public bool ticketMemberActive { get; set; }
        public int ticketMemberTypeID { get; set; }
    
        public virtual ICollection<ticket> tickets { get; set; }
        public virtual ticketMemberType ticketMemberType { get; set; }
    }
}
