//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketMemberType
    {
        public ticketMemberType()
        {
            this.ticketMembers = new HashSet<ticketMember>();
            this.tran_priceProfile = new HashSet<tran_priceProfile>();
        }
    
        public int ticketMemberTypeID { get; set; }
        public string ticketMemberTypeName { get; set; }
        public string ticketMemberTypeComment { get; set; }
        public bool ticketMemberTypeActive { get; set; }
    
        public virtual ICollection<ticketMember> ticketMembers { get; set; }
        public virtual ICollection<tran_priceProfile> tran_priceProfile { get; set; }
    }
}
