//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_priceProfileType
    {
        public tran_priceProfileType()
        {
            this.tran_priceProfile = new HashSet<tran_priceProfile>();
        }
    
        public int priceProfileTypeID { get; set; }
        public string priceProfileTypeName { get; set; }
    
        public virtual ICollection<tran_priceProfile> tran_priceProfile { get; set; }
    }
}
