//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_priceDialy
    {
        public int priceDialyID { get; set; }
        public double priceDialyRate { get; set; }
        public string priceDayName { get; set; }
    }
}
