//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_priceProfileHour
    {
        public int priceProfileHourID { get; set; }
        public int priceProfileHourNo { get; set; }
        public double priceProfileHourRate { get; set; }
        public int priceProfileDayID { get; set; }
    
        public virtual tran_priceProfileDay tran_priceProfileDay { get; set; }
    }
}
