//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_priceProfile
    {
        public tran_priceProfile()
        {
            this.tran_priceProfileChangeLog = new HashSet<tran_priceProfileChangeLog>();
            this.tran_priceProfileChangeLog1 = new HashSet<tran_priceProfileChangeLog>();
            this.tran_priceProfileDay = new HashSet<tran_priceProfileDay>();
            this.tran_transaction = new HashSet<tran_transaction>();
        }
    
        public int priceProfileID { get; set; }
        public string priceProfileName { get; set; }
        public bool priceProfileActive { get; set; }
        public int carTypeID { get; set; }
        public bool priceProfileFlooringMode { get; set; }
        public double priceProfileLostCardFee { get; set; }
        public int ticketMemberTypeID { get; set; }
        public double priceProfileOverNightFee { get; set; }
        public Nullable<int> priceProfileMultiOverNightMode { get; set; }
        public int priceProfileTypeID { get; set; }
        public bool priceProfileDiscountInCashier { get; set; }
        public int priceProfileColor { get; set; }
        public int priceProfileFlooringOffset { get; set; }
    
        public virtual car_carType car_carType { get; set; }
        public virtual ticketMemberType ticketMemberType { get; set; }
        public virtual tran_priceProfileType tran_priceProfileType { get; set; }
        public virtual ICollection<tran_priceProfileChangeLog> tran_priceProfileChangeLog { get; set; }
        public virtual ICollection<tran_priceProfileChangeLog> tran_priceProfileChangeLog1 { get; set; }
        public virtual ICollection<tran_priceProfileDay> tran_priceProfileDay { get; set; }
        public virtual ICollection<tran_transaction> tran_transaction { get; set; }
    }
}
