//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_transactionType
    {
        public tran_transactionType()
        {
            this.tran_transaction = new HashSet<tran_transaction>();
        }
    
        public int transactionTypeID { get; set; }
        public string transactionTypeName { get; set; }
    
        public virtual ICollection<tran_transaction> tran_transaction { get; set; }
    }
}
