//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_emergencyType
    {
        public int emergencyTypeID { get; set; }
        public string emergencyTypeName { get; set; }
        public bool IsGateInUsed { get; set; }
        public bool IsGateOutUsed { get; set; }
    }
}
