//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_priceMonthly
    {
        public int priceMonthlyID { get; set; }
        public string priceMonthlyName { get; set; }
        public int priceMonthlyValue { get; set; }
        public bool priceMonthlyActive { get; set; }
    }
}
