//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_transaction
    {
        public tran_transaction()
        {
            this.tran_priceProfileChangeLog = new HashSet<tran_priceProfileChangeLog>();
        }
    
        public int transactionID { get; set; }
        public System.DateTime transactionChkIn { get; set; }
        public string priceProfileName { get; set; }
        public int sysUserID_ChkIn { get; set; }
        public Nullable<int> accountingID { get; set; }
        public Nullable<int> numOfPerson { get; set; }
        public Nullable<int> realNumOfPerson { get; set; }
        public Nullable<int> transactionTypeID { get; set; }
        public string transactionParkingTime { get; set; }
        public Nullable<System.DateTime> transactionLastUpdate { get; set; }
        public Nullable<int> priceProfileID { get; set; }
        public Nullable<System.DateTime> transactionChkOut { get; set; }
        public string transactionComment { get; set; }
        public string ticketNumber { get; set; }
        public string carPlateNumber { get; set; }
        public string carPlateCity { get; set; }
        public Nullable<int> sysUserID_ChkOut { get; set; }
        public Nullable<int> gateID_IN { get; set; }
        public Nullable<int> gateID_OUT { get; set; }
        public Nullable<bool> transactionIsLostCard { get; set; }
    
        public virtual accounting accounting { get; set; }
        public virtual sysGate sysGate { get; set; }
        public virtual sysGate sysGate1 { get; set; }
        public virtual sysUser sysUser { get; set; }
        public virtual sysUser sysUser1 { get; set; }
        public virtual tran_priceProfile tran_priceProfile { get; set; }
        public virtual ICollection<tran_priceProfileChangeLog> tran_priceProfileChangeLog { get; set; }
        public virtual tran_transactionType tran_transactionType { get; set; }
    }
}
