//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran_priceProfileChangeLog
    {
        public int priceProfileChangeLogID { get; set; }
        public int priceProfileOldID { get; set; }
        public int priceProfileNewID { get; set; }
        public int transactionID { get; set; }
        public int sysUserID { get; set; }
        public System.DateTime priceProfileChangeLogDateTime { get; set; }
        public string priceProfileChangeLogComment { get; set; }
    
        public virtual sysUser sysUser { get; set; }
        public virtual tran_priceProfile tran_priceProfile { get; set; }
        public virtual tran_priceProfile tran_priceProfile1 { get; set; }
        public virtual tran_transaction tran_transaction { get; set; }
    }
}
