//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ticketInfo
    {
        public int ticketID { get; set; }
        public Nullable<int> ticketMemberID { get; set; }
        public string ticketNumber { get; set; }
        public string ticketMemberName { get; set; }
        public int ticketTypeID { get; set; }
        public string ticketTypeName { get; set; }
        public System.DateTime ticketStartDate { get; set; }
        public System.DateTime ticketExpiryDate { get; set; }
        public bool ticketActive { get; set; }
        public int ticketRemainTimes { get; set; }
        public double ticketCredit { get; set; }
        public System.DateTime ticketDateUpdate { get; set; }
        public string sysUserName { get; set; }
        public int userID_Create { get; set; }
        public string carPlateNumber { get; set; }
        public string carBrandName { get; set; }
        public string carTypeName { get; set; }
        public string provinceName { get; set; }
        public string ticketMemberTypeName { get; set; }
        public string carModel { get; set; }
        public string carColor { get; set; }
        public string ticketMemberTel { get; set; }
        public string ticketMemberEmail { get; set; }
        public string ticketMemberAddr { get; set; }
        public Nullable<int> carID { get; set; }
        public string ticketRemainDay { get; set; }
        public Nullable<int> ticketRemainSecond { get; set; }
        public Nullable<int> priceMonthlyID { get; set; }
    }
}
