//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_EStamp_log
    {
        public int priceProfileChangeLogID { get; set; }
        public int transactionID { get; set; }
        public string ticketNumber { get; set; }
        public string carPlateNumber { get; set; }
        public System.DateTime priceProfileChangeLogDateTime { get; set; }
        public string oldProfile { get; set; }
        public string newProfile { get; set; }
        public string sysUserName { get; set; }
        public string priceProfileChangeLogComment { get; set; }
    }
}
