//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_parkingAreaInfo
    {
        public int parkingAreaID { get; set; }
        public string parkingAreaName { get; set; }
        public int parkingAreaSlotAvaliable { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> parkingAreaSlotRemain { get; set; }
    }
}
