//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_accounting_all
    {
        public int accountingID { get; set; }
        public string ticketNumber { get; set; }
        public double accountingPrices { get; set; }
        public double accountingDiscount { get; set; }
        public double accountingReceive { get; set; }
        public System.DateTime accountingDateTime { get; set; }
        public string ticketMemberName { get; set; }
        public string carPlateNumber { get; set; }
        public int userID { get; set; }
        public string sysUserName { get; set; }
        public string accountingTypeName { get; set; }
        public int accountingTypeID { get; set; }
    }
}
