//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Emergency_ALL
    {
        public int transactionID { get; set; }
        public System.DateTime transactionChkIn { get; set; }
        public Nullable<System.DateTime> transactionChkOut { get; set; }
        public string gateIn { get; set; }
        public string gateOut { get; set; }
        public string sysUserIn { get; set; }
        public string sysUserOut { get; set; }
        public System.DateTime transactionLastUpdate { get; set; }
        public string transactionComment { get; set; }
    }
}
