//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_accessright
    {
        public int permissionID { get; set; }
        public string permissionName { get; set; }
        public string sysUserLoginName { get; set; }
        public Nullable<int> sysUserID { get; set; }
        public Nullable<int> sysUserTypeID { get; set; }
        public string sysUserTypeName { get; set; }
        public Nullable<bool> sysUserTypePermissionRead { get; set; }
        public Nullable<bool> sysUserTypePermissionNew { get; set; }
        public Nullable<bool> sysUserTypePermissionEdit { get; set; }
        public Nullable<bool> sysUserTypePermissionDel { get; set; }
    }
}
