//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_VMS_log_stayTime
    {
        public int logId { get; set; }
        public string visitorName { get; set; }
        public string visitorNote { get; set; }
        public string visitorTel { get; set; }
        public string visitorCarNumber { get; set; }
        public string visitorEmail { get; set; }
        public string visit_purpose { get; set; }
        public string visit_person_id { get; set; }
        public string visitorCompany { get; set; }
        public Nullable<System.DateTime> visitorChkIn { get; set; }
        public Nullable<System.DateTime> visitorChkOut { get; set; }
        public string tosee_name { get; set; }
        public string tosee_addr { get; set; }
        public string ticketId { get; set; }
        public byte[] visitorImg1 { get; set; }
        public byte[] visitorImg2 { get; set; }
        public byte[] visitorImg3 { get; set; }
        public string visitorCardLocation { get; set; }
        public string visitArea { get; set; }
        public Nullable<bool> lostCard { get; set; }
        public Nullable<int> MinuteDiff { get; set; }
    }
}
