//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_priceProfile
    {
        public int priceProfileID { get; set; }
        public int priceProfileDayID { get; set; }
        public string priceProfileName { get; set; }
        public bool priceProfileActive { get; set; }
        public int carTypeID { get; set; }
        public bool priceProfileFlooringMode { get; set; }
        public double priceProfileLostCardFee { get; set; }
        public double priceProfileOverNightFee { get; set; }
        public Nullable<int> priceProfileMultiOverNightMode { get; set; }
        public int ticketMemberTypeID { get; set; }
        public int priceProfileTypeID { get; set; }
        public int priceProfileDayFreeTime { get; set; }
        public double priceProfileDayServiceCharge { get; set; }
        public int priceProfileDayNumOfDay { get; set; }
        public int priceProfileHourID { get; set; }
        public int priceProfileHourNo { get; set; }
        public double priceProfileHourRate { get; set; }
        public bool priceProfileDiscountInCashier { get; set; }
        public int priceProfileColor { get; set; }
        public int priceProfileFlooringOffset { get; set; }
    }
}
