//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_EStamp_log_DisTinc_transID
    {
        public Nullable<int> Last_priceProfileChangeLogID { get; set; }
        public int transactionID { get; set; }
        public string ticketNumber { get; set; }
        public string carPlateNumber { get; set; }
        public Nullable<System.DateTime> priceProfileChangeLogDateTime { get; set; }
        public string priceProfileName { get; set; }
        public string sysUserName { get; set; }
    }
}
